# Generated by Django 6.0.6 on 2026-06-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('afternoon_name', models.CharField(default='Afternoon meal', max_length=80)),
                ('afternoon_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('night_name', models.CharField(default='Night meal', max_length=80)),
                ('night_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('note', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
